### ISSUE TITLE
Novo Certificado A1 para Emissão de DAEs: atualização de sistemas.

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/certificado-serpro#2]
- [x] SISWEB
- [x] S2DOC
- [x] SEDAE
- [x] SACS
- [x] Crontab

**Comment by rmadev-master** [comment]
Após adicionar os arquivos nas pastas do **nusoap**, deve-se adicionar **permissão 777** aos arquivos **.cer** e **.key**.

**Comment by rmadev-master** [comment]
SISWEB atualizado.

**Comment by rmadev-master** [comment]
S2DOC atualizado.

**Comment by rmadev-master** [comment]
SEDAE atualizado.

**Comment by rmadev-master** [comment]
Crontab atualizado.

**Comment by rmadev-master** [comment]
SACS atualizado.

**Comment by rmadev-master** [comment]
Todas as aplicações foram atualizadas.
